Project CUSTOMER {
  name: "Customer Data Model"
  version: "1"
}

Table CUSTOMER_SCHEMA.CUSTOMER [headercolor: #34db95] {
    C_CUSTKEY NUMBER [pk, note: "Customer primary key"]
    C_NAME STRING [note: "Customer name"]
    C_ADDRESS STRING [note: "Customer address"]
    C_NATIONKEY NUMBER [ref: > CUSTOMER_SCHEMA.NATION.N_NATIONKEY, note: "Nation key"]
    C_PHONE STRING [note: "Customer phone number"]
    C_ACCTBAL NUMBER [note: "Account balance"]
    C_MKTSEGMENT STRING [note: "Market segment"]
    C_COMMENT STRING [note: "Free text comment"]

    Note: "Customer data as defined by TPC-H"
}

Table CUSTOMER_SCHEMA.NATION [headercolor: #34db95] {
    N_NATIONKEY NUMBER [pk, note: "Nation primary key"]
    N_NAME STRING [note: "Nation name"]
    N_REGIONKEY NUMBER [note: "Region key"]
    N_COMMENT STRING [note: "Free text comment"]

    Note: "Nation data as defined by TPC-H"
}

Table CUSTOMER_SCHEMA.ORDERS [headercolor: #34db95] {
    O_ORDERKEY NUMBER [pk, note: "Order primary key"]
    O_CUSTKEY NUMBER [ref: > CUSTOMER_SCHEMA.CUSTOMER.C_CUSTKEY, note: "Customer key"]
    O_ORDERSTATUS STRING [note: "Order status"]
    O_TOTALPRICE NUMBER [note: "Total order price"]
    O_ORDERDATE DATE [note: "Order date"]
    O_ORDERPRIORITY STRING [note: "Order priority"]
    O_CLERK STRING [note: "Clerk identifier"]
    O_SHIPPRIORITY NUMBER [note: "Shipping priority"]
    O_COMMENT STRING [note: "Free text comment"]

    Note: "Orders data as defined by TPC-H"
}